# Generated by Django 6.0.6 on 2026-06-25 20:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_order_order_type_order_pickup_time_profile_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount for this order line (price × qty)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_number",
            field=models.CharField(
                blank=True, help_text="e.g. LICET-20260626-0001", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                help_text="Payment status from Razorpay flow",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_slot",
            field=models.CharField(
                blank=True, help_text="e.g. 1:00 PM - 1:15 PM", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="qr_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, help_text="Unique QR pickup token"
            ),
        ),
    ]
