# Generated by Django 6.0.6 on 2026-06-25 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="Razorpay event ID for idempotency",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(help_text="e.g. payment.captured", max_length=50),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("payload", models.JSONField(help_text="Full webhook payload")),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="Signature verified"),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, help_text="Successfully processed"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Processing errors"),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "payment_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_group",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Order reference like LCT-0001 that groups multiple Order rows",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in rupees", max_digits=10
                    ),
                ),
                (
                    "amount_paise",
                    models.PositiveIntegerField(
                        default=0, help_text="Amount in paise sent to Razorpay"
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("razorpay_signature", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("upi", "UPI"),
                            ("netbanking", "Net Banking"),
                            ("wallet", "Wallet"),
                            ("emi", "EMI"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Signature verification passed"
                    ),
                ),
                (
                    "webhook_received",
                    models.BooleanField(
                        default=False, help_text="Webhook confirmation received"
                    ),
                ),
                (
                    "webhook_event",
                    models.CharField(
                        blank=True,
                        help_text="Last webhook event type received",
                        max_length=50,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Error messages or notes"),
                ),
                (
                    "transaction_time",
                    models.DateTimeField(
                        blank=True, help_text="When payment was completed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
